### ISSUE TITLE
Is PoseAug able to produce some special poses while doing the augmentation?

### ISSUE THREAD

**Issue by AndyVerne** [jfzhang95/PoseAug#32]
Hi, thanks so much for your great job. I learn a lot from this project.

I learned that your code indicates "that fix bone segment from pelvis to thorax to avoid pure rotation of whole body without ba changes." 

So at the mean time, according to this condition that fix the bone segment from pelvis to thorax, I am curious about the PoseAug whether can produce some special types of poses like "lying down" , "push ups" and so on.

I'm looking forward to your replies.

**Comment by Garfield-kh** [comment]
Hi, thank you for the interest!
To control the augmentation process for producing special types of poses like "lying down", there are several approaches that may help.

1. If you have a 2D pose dataset D2 containing "lying down", replace the `target_2d_loader` by D2 so that the `model_d2d `can learn from such data and guide the `augmentor`. 
2. Similarly, if you have a 3D pose dataset D3 containing "lying down", replace the `target_3d_loader `by D3 so that the `model_d3d `can learn from such data and guide the `augmentor`. 
3. You may also considering action [conditioned pose generation](https://github.com/Mathux/ACTOR) (i.e. Conditional GAN) if you have the pose data with labels as conditional input.

Hope this helps.
Thank you~

**Comment by AndyVerne** [comment]
Thanks for your replies! It does a lot help to me!
Hope you have a great day :)
