### ISSUE TITLE
About GAN mode collapse prevention

### ISSUE THREAD

**Issue by MichelGao96** [jfzhang95/PoseAug#35]
Hello,
I am going through your code lately. I am freshman to GAN and I found two functions difficult to understand.
In the "train_gan" fonction from [model_gan_train.py](https://github.com/jfzhang95/PoseAug/blob/main/function_poseaug/model_gan_train.py), you used:
1.  "diff_loss" function to encourage diversity and regulate loss for ba\rt to avoid gan collapse.
2.  "get_feedback_loss" function to generate harder case.

But what kind of strategy have you used for these two purposes? 
I can see from "diff_loss" that you particularly selected some loss by some standards, and how does this help prevent gan collapse?

In "get_feedback_loss", why are there "weights" applied to "posenet_loss" ? What is the purpose of "feedback_loss", selecting losses from cases that is too hard?

I will appreciate your answer.
Thanks a lot!

**Comment by Garfield-kh** [comment]
Hi, thank you for the interest!

`I can see from "diff_loss" that you particularly selected some loss by some standards, and how does this help prevent gan collapse?
`
There is a possibility that the augmentor does nothing to the original data, such as BA operation with 0 degree rotation. In this way, the discriminator can still be fooled since the augmented pose is the same as the original data. To avoid such cases, we use diff_loss to encourage novel pose generation.

`In "get_feedback_loss", why are there "weights" applied to "posenet_loss" ? What is the purpose of "feedback_loss", selecting losses from cases that is too hard?
`
The weights here is to a balance factor for arm and leg, where the joints close to torso is 5 (e.g., shoulder) and the joints far from torso is 1 (e.g., hand). This is from the observation that the average error from hands is larger than shoulders.

Hope this helps.
Thank you~
