### ISSUE TITLE
Evaluation on MPI-INF-3DHP

### ISSUE THREAD

**Issue by gurkirt** [jfzhang95/PoseAug#4]
I am assuming your training data is H36M poses not the meshes and you are evaluating on pose on MPI-INF-3DHP as well, without using SMPL parameters from both.
Further, you apply poseAug on 2D and 3D poses of H36M to get training pairs. At that time you would use 16 joint skeleton model of 

So, my questions are how do you evaluate given that the skeleton model of MPI-INF-3DHP is 23 joints models and some basic joints have no correspondence from H36M to MPI-INF-3DHP, e.g. Thorex, head_top, Spine are not there in H36M, however, H36M have Neck and Head joint.

 How did you evaluate MPI-INF-3DHP in a cross-dataset-testing-scenrio given skeleton model discrepancy? 

I guess you only use a subset of joints to evaluate?

**Comment by Garfield-kh** [comment]
Thanks for your interest in this work. There are some skeleton joint definitions mismatched in those different pose datasets. 

In our experiment, we use 16 joints (removed Neck/Nose) in H36M following previous work SemGCN. For the visualization of skeleton joint definition in H36M, you may refer to this figure: 
https://github.com/Nicholasli1995/EvoSkeleton/blob/master/imgs/hierarchical.jpg. The Thorax and Spine joints are included in the H36M dataset.

When performing evaluation or inference in the target datasets (e.g., 3DHP, 3DPW):
1. We assume the same joint definitions of Pelvis, Hips, Knees, Feet, Shoulders, Elbows, Wrists between the source and target datasets.
2. When missing joint definitions in Thorax and Spine, we treat Thorax as the middle point of left and right Shoulders and treat Spine as the middle point of Pelvis and Thorax. 
3. When missing joint definition in Head, if there is Head_top defined in the target data, we use Heat_top as the Head joint; otherwise, we generate the Head joint by extending the vector from Pelvis to Thorax in a fixed ratio (0.4).

In this way, both the source and target datasets have the same skeleton joint configuration. We also tried only use the matching skeleton joints in both datasets (i.e., only use 14 joints for training and evaluation), the results are similar.

**Comment by zlou** [comment]
Hi, thanks for the through description and releasing your code. My understanding is that you were mainly talking about 3D poses here? My main question is what 2D inputs you used. My understanding is that for 3DHP you would use the projection to general the 2D poses. For 3DPW dataset, you were using the 2D detection results provided by the dataset. So in this case, a separate model with COCO kpt as input will be trained for 3DPW. Is that correct?

**Comment by Garfield-kh** [comment]
Hi, @zlou  thank you for the interst.
All the 2D 3D pose follow the same joint setting.
